#!/usr/bin/env python3
"""
CSV Converter for FastFractalAnalyzer Plotting Compatibility
============================================================

Converts FractalParameterAI CSV output format to be compatible with
FastFractalAnalyzer plotting scripts (rt_plotter.py).

Key Transformations:
-------------------
1. Time conversion: seconds → milliseconds (multiply by 1000)
2. Multifractal column renaming:
   - multifractal_d0 → D0_capacity
   - multifractal_d1 → D1_information
   - multifractal_d2 → D2_correlation
3. Compute total_rms from u_rms and v_rms: sqrt(u_rms² + v_rms²)
4. Map mixing_width → dalziel_h (physically equivalent metric)
5. Add empty thickness column (optional field)

Usage:
------
    python convert_csv_for_plotting.py input.csv output.csv
    python convert_csv_for_plotting.py input.csv  # Auto-generates output name
    python convert_csv_for_plotting.py --batch *.csv  # Convert multiple files

Author: Generated by Claude for FractalParameterAI project
Date: 2025-10-31
"""

import argparse
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional
import sys


def convert_csv(input_file: Path, output_file: Optional[Path] = None,
                verbose: bool = True) -> bool:
    """
    Convert FractalParameterAI CSV to FastFractalAnalyzer plotting format.

    Args:
        input_file: Path to input CSV file
        output_file: Path to output CSV file (auto-generated if None)
        verbose: Print conversion details

    Returns:
        True if successful, False otherwise
    """
    if verbose:
        print(f"📂 Reading: {input_file}")

    try:
        # Read input CSV
        df = pd.read_csv(input_file)

        if verbose:
            print(f"   ✓ Loaded {len(df)} rows, {len(df.columns)} columns")

        # ==============================================
        # 1. Time conversion: seconds → milliseconds
        # ==============================================
        if 'time' in df.columns:
            # Check if already in milliseconds (heuristic: max value > 100)
            if df['time'].max() < 100:
                if verbose:
                    print(f"   🕐 Converting time: seconds → milliseconds")
                df['time'] = df['time'] * 1000.0
            else:
                if verbose:
                    print(f"   ℹ️  Time already in milliseconds (skipped conversion)")

        # ==============================================
        # 2. Multifractal column renaming
        # ==============================================
        multifractal_map = {
            'multifractal_d0': 'D0_capacity',
            'multifractal_d1': 'D1_information',
            'multifractal_d2': 'D2_correlation'
        }

        renamed_count = 0
        for old_name, new_name in multifractal_map.items():
            if old_name in df.columns:
                df.rename(columns={old_name: new_name}, inplace=True)
                renamed_count += 1

        if verbose and renamed_count > 0:
            print(f"   📊 Renamed {renamed_count} multifractal columns")

        # ==============================================
        # 3. Compute total_rms from u_rms and v_rms
        # ==============================================
        if 'u_rms' in df.columns and 'v_rms' in df.columns:
            # Only compute if total_rms doesn't already exist
            if 'total_rms' not in df.columns:
                df['total_rms'] = np.sqrt(df['u_rms']**2 + df['v_rms']**2)
                if verbose:
                    print(f"   🔢 Computed total_rms = sqrt(u_rms² + v_rms²)")
            else:
                if verbose:
                    print(f"   ℹ️  total_rms already exists (skipped)")
        elif verbose:
            print(f"   ⚠️  u_rms or v_rms not found (total_rms not computed)")

        # ==============================================
        # 4. Map mixing_width → dalziel_h
        # ==============================================
        if 'mixing_width' in df.columns:
            # Create dalziel_h as copy of mixing_width
            df['dalziel_h'] = df['mixing_width'].copy()
            if verbose:
                print(f"   📏 Mapped mixing_width → dalziel_h")
        elif verbose:
            print(f"   ⚠️  mixing_width not found (dalziel_h not created)")

        # ==============================================
        # 5. Add empty thickness column (optional)
        # ==============================================
        if 'thickness' not in df.columns:
            df['thickness'] = np.nan
            if verbose:
                print(f"   ➕ Added empty thickness column (optional field)")

        # ==============================================
        # 6. Generate output filename if not provided
        # ==============================================
        if output_file is None:
            # Auto-generate: input_name → input_name_plotting.csv
            stem = input_file.stem
            output_file = input_file.parent / f"{stem}_plotting.csv"

        # ==============================================
        # 7. Save converted CSV
        # ==============================================
        df.to_csv(output_file, index=False)

        if verbose:
            print(f"   ✅ Saved: {output_file}")
            print(f"   📊 Output: {len(df)} rows, {len(df.columns)} columns")

        return True

    except Exception as e:
        print(f"   ❌ Error converting {input_file}: {e}")
        import traceback
        traceback.print_exc()
        return False


def validate_required_columns(df: pd.DataFrame, verbose: bool = True) -> bool:
    """
    Check if converted CSV has required columns for plotting.

    Args:
        df: Converted dataframe
        verbose: Print validation details

    Returns:
        True if valid, False otherwise
    """
    required = ['time', 'fractal_dimension']
    missing = [col for col in required if col not in df.columns]

    if missing:
        if verbose:
            print(f"   ⚠️  Missing required columns: {missing}")
        return False

    optional = ['fractal_r_squared', 'mixing_width', 'u_rms', 'v_rms',
                'total_rms', 'dalziel_h', 'thickness',
                'D0_capacity', 'D1_information', 'D2_correlation']

    found_optional = [col for col in optional if col in df.columns]

    if verbose:
        print(f"   ✓ Required columns: {required}")
        print(f"   ✓ Optional columns found: {len(found_optional)}/{len(optional)}")

    return True


def batch_convert(input_patterns: list, verbose: bool = True) -> dict:
    """
    Convert multiple CSV files in batch mode.

    Args:
        input_patterns: List of file patterns or paths
        verbose: Print progress

    Returns:
        Dictionary with conversion statistics
    """
    from glob import glob

    # Expand patterns
    all_files = []
    for pattern in input_patterns:
        if '*' in pattern:
            all_files.extend(glob(pattern))
        else:
            all_files.append(pattern)

    all_files = [Path(f) for f in all_files if f.endswith('.csv')]

    if verbose:
        print(f"🔄 Batch conversion: {len(all_files)} files")
        print("=" * 70)

    results = {'success': 0, 'failed': 0, 'files': []}

    for i, input_file in enumerate(all_files, 1):
        if verbose:
            print(f"\n[{i}/{len(all_files)}] {input_file.name}")

        success = convert_csv(input_file, verbose=verbose)

        if success:
            results['success'] += 1
            results['files'].append(str(input_file))
        else:
            results['failed'] += 1

    if verbose:
        print("\n" + "=" * 70)
        print(f"✅ Batch complete: {results['success']} succeeded, {results['failed']} failed")

    return results


def main():
    """Command-line interface."""
    parser = argparse.ArgumentParser(
        description='Convert FractalParameterAI CSV to FastFractalAnalyzer plotting format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single file conversion (auto-generate output name)
  python convert_csv_for_plotting.py temporal_evolution.csv

  # Specify output filename
  python convert_csv_for_plotting.py temporal_evolution.csv output.csv

  # Batch conversion with wildcard
  python convert_csv_for_plotting.py --batch results_*/temporal_evolution.csv

  # Quiet mode (minimal output)
  python convert_csv_for_plotting.py --quiet input.csv
        """
    )

    parser.add_argument('input_file', nargs='+',
                       help='Input CSV file(s). Use --batch for multiple files.')
    parser.add_argument('output_file', nargs='?', default=None,
                       help='Output CSV file (auto-generated if not specified)')
    parser.add_argument('--batch', action='store_true',
                       help='Batch mode: convert multiple files')
    parser.add_argument('--quiet', '-q', action='store_true',
                       help='Quiet mode (minimal output)')
    parser.add_argument('--validate', action='store_true',
                       help='Validate output CSV after conversion')

    args = parser.parse_args()

    verbose = not args.quiet

    # ==============================================
    # Batch mode
    # ==============================================
    if args.batch:
        results = batch_convert(args.input_file, verbose=verbose)
        sys.exit(0 if results['failed'] == 0 else 1)

    # ==============================================
    # Single file mode
    # ==============================================
    if len(args.input_file) > 1 and args.output_file is None:
        print("❌ Error: Multiple input files require --batch mode")
        sys.exit(1)

    input_file = Path(args.input_file[0])
    output_file = Path(args.output_file) if args.output_file else None

    if not input_file.exists():
        print(f"❌ Error: Input file not found: {input_file}")
        sys.exit(1)

    # Convert
    success = convert_csv(input_file, output_file, verbose=verbose)

    if not success:
        sys.exit(1)

    # Validate if requested
    if args.validate:
        if verbose:
            print(f"\n🔍 Validating output...")

        output_path = output_file if output_file else input_file.parent / f"{input_file.stem}_plotting.csv"
        df = pd.read_csv(output_path)

        if validate_required_columns(df, verbose=verbose):
            if verbose:
                print(f"   ✅ Validation passed")
        else:
            if verbose:
                print(f"   ⚠️  Validation warnings (output may still work)")

    if verbose:
        print(f"\n{'='*70}")
        print(f"✅ Conversion complete!")
        print(f"\nNext steps:")
        print(f"  1. Use plot_rt_results.py to generate plots:")

        output_path = output_file if output_file else input_file.parent / f"{input_file.stem}_plotting.csv"
        print(f"     python plot_rt_results.py {output_path}")
        print(f"\n  2. Or use the FastFractalAnalyzer plotting framework")
        print(f"{'='*70}")


if __name__ == '__main__':
    main()
